const { analyzeText, tokenize, sentiment, readability, tfidf, topics } = require('../src/analysis/text');
const profile = posts => ({ posts: { data: posts } });
test('no posts abstains; missing message does not invent a value', () => { expect(analyzeText(profile([])).features.sentiment.value).toBeNull(); expect(analyzeText(profile([{ id: '1' }])).features.topics.status).toBe('insufficient_evidence'); });
test('one post has per-post sentiment, negation and a valid denominator', () => { expect(sentiment('This is not good.').label).toBe('negative'); const value = analyzeText(profile([{ id: 'p', message: 'I love this 😊' }])).features.sentiment.value; expect(value.distribution.positive).toBe(1); expect(value.scoredN).toBe(1); });
test('non-English text is unscored and unicode survives tokenization', () => { expect(sentiment('مجھے کتابیں پسند ہیں').label).toBe('unscored'); expect(sentiment('Me encanta la comida').score).toBeNull(); expect(tokenize('Éducation کتاب')).toContain('éducation'); });
test('emoji-only and empty input are distinct', () => { expect(sentiment('😊😊').score).toBe(2); expect(sentiment('').label).toBe('unscored'); });
test('readability uses raw words including stopwords and at least three sentences', () => { expect(readability('This is good.')).toBeNull(); const text = 'This is a good day. This is a bad day. This is a new day.'; const r = readability(text); expect(r.words).toBe(15); expect(r.sentences).toBe(3); expect(r.fleschReadingEase).toBeCloseTo(117.16); });
test('taxonomy uses whole tokens and returns evidence', () => { expect(topics([{ id: 'a', message: 'I said brunch in snow' }])).toEqual([]); expect(topics([{ id: 'a', message: 'I enjoy technology and music' }]).map(t => t.topic)).toEqual(['technology', 'arts']); });
test('TF-IDF is normalized and uses document frequency', () => { const items = tfidf([{ id: 'a', message: 'robot robot common' }, { id: 'b', message: 'common' }]); expect(items.find(x => x.term === 'robot').weight).toBeCloseTo(2 / 3 * (Math.log(3 / 2) + 1)); expect(items.find(x => x.term === 'common').postIds).toEqual(['a', 'b']); });
